[package]
name = "s3etag"
version = "0.1.1"
authors = ["rodrifs"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
md5 = "0.7"
clap = "2.33"
rayon = "1.3"
